FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /src

# Copy source code
COPY Interlude.Web/ ./Interlude.Web
COPY Prelude/ ./Prelude
COPY Percyqaz.Common/ ./Percyqaz.Common

WORKDIR ./Interlude.Web/server

RUN dotnet restore
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:7.0
WORKDIR /docker_root
COPY --from=build-env /src/Interlude.Web/server/out .
RUN mkdir -p /docker_root/secrets
ENTRYPOINT ["dotnet", "Interlude.Web.Server.dll"]