FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env
WORKDIR /src

COPY online ./online
COPY prelude/ ./prelude
COPY libraries/Percyqaz.Common/ ./libraries/Percyqaz.Common
COPY libraries/Percyqaz.Data/ ./libraries/Percyqaz.Data

WORKDIR ./online/server

RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:9.0
WORKDIR /docker_root
COPY --from=build-env /src/online/server/out .
RUN mkdir -p /docker_root/secrets
ENTRYPOINT ["dotnet", "Interlude.Web.Server.dll"]