FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /src

# Copy source code
COPY online ./online
COPY prelude/ ./prelude
COPY libraries/Percyqaz.Common/ ./libraries/Percyqaz.Common

WORKDIR ./online/server

RUN dotnet restore
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:7.0
WORKDIR /docker_root
COPY --from=build-env /src/online/server/out .
RUN mkdir -p /docker_root/secrets
ENTRYPOINT ["dotnet", "Interlude.Web.Server.dll"]