name: B2 Authorize CF Worker
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
    
jobs:
  build:
    if: github.repository == 'YAVSRG/YAVSRG'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout the repository content

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Execute script
        env:
          BUCKET_SOURCE_ID: ${{ secrets.BUCKET_SOURCE_ID }}
          B2_APP_KEY: ${{ secrets.B2_APP_KEY }}
          B2_APP_KEY_ID: ${{ secrets.B2_APP_KEY_ID }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_WORKER_API: ${{ secrets.CF_WORKER_API }}
        run: python online/b2AuthorizeCfWorker.py