name: Continuous integration

on:
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: write
  pull-requests: write
    
jobs:
  pull-request-ci-checks:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Ensure everything builds
      run: dotnet build
        
    - name: Run unit tests
      run: |
        cd scripts
        chmod +x ./run_tests.sh
        ./run_tests.sh
        
    - name: Run formatting checks
      run: fantomas --check .
        
    - name: Approve PRs from Percyqaz if checks pass
      if: ${{ github.actor == 'percyqaz' }}
      run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}